apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: service-port
      port: {{ .Values.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.targetPort }}
  selector:
    app: techtrends
  type: ClusterIP
status:
  loadBalancer: {}